name: Build and Deploy to AKS

on:
  push:
    branches: [main]

env:
  AZURE_CONTAINER_REGISTRY: acrlabk8s.azurecr.io
  IMAGE_NAME: webapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: azure
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login via OIDC
      uses: azure/login@v1.6.1  # ✅ supports 'federated'
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Docker Login to ACR
      run: az acr login --name acrlabk8s
  
    - name: Build Docker image
      run: |
        docker build -t $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ github.sha }} .
        docker push $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ github.sha }}

    - name: Set up kubectl
      uses: azure/aks-set-context@v3
      with:
        resource-group: rg-aks-lab
        cluster-name: acrlabk8s

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/webapp webapp=$AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ github.sha }}
